#include <iostream>
#include<bits/stdc++.h>
#include <string>
using namespace std;
void L(string &s,int zamik);
void D(string &s,int zamik);
void Z(string &s,char znak1,char znak2);
int main()
{
    string sporocilo="ihjiyrijuwdhmtmigcmcvezehazazflfwnrmzvpxssymhjweyzbsjbzgvynntymsisrtfrqlktuakxyqlckmtjalcuxnyakgudon";
    Z(sporocilo, 's', 'h');
    Z(sporocilo, 'w', 'g');
    Z(sporocilo, 'p', 'u');
    Z(sporocilo, 'x', 'x');
    D(sporocilo, 58);
    L(sporocilo, 100);
    Z(sporocilo, 'e', 'g');
    Z(sporocilo, 'k', 'v');
    D(sporocilo, 63);
    Z(sporocilo, 'd', 'b');
    L(sporocilo, 52);
    Z(sporocilo, 'l', 'y');
    Z(sporocilo, 'm', 'u');
    Z(sporocilo, 's', 'e');
    Z(sporocilo, 'q', 'h');
    D(sporocilo, 88);
    L(sporocilo, 24);
    Z(sporocilo, 'k', 'e');
    L(sporocilo, 92);
    D(sporocilo, 6);
    Z(sporocilo, 'x', 'z');
    D(sporocilo, 99);
    Z(sporocilo, 'v', 'p');
    L(sporocilo, 58);
    L(sporocilo, 90);
    L(sporocilo, 70);
    L(sporocilo, 38);
    L(sporocilo, 28);
    D(sporocilo, 28);
    D(sporocilo, 87);
    L(sporocilo, 86);
    Z(sporocilo, 'w', 'n');
    D(sporocilo, 92);
    Z(sporocilo, 'l', 'c');
    D(sporocilo, 51);
    L(sporocilo, 67);
    D(sporocilo, 74);
    D(sporocilo, 66);
    D(sporocilo, 46);
    D(sporocilo, 65);
    L(sporocilo, 70);
    D(sporocilo, 55);
    D(sporocilo, 18);
    D(sporocilo, 30);
    Z(sporocilo, 'w', 'n');
    L(sporocilo, 25);
    D(sporocilo, 14);
    L(sporocilo, 68);
    L(sporocilo, 77);
    L(sporocilo, 32);
    L(sporocilo, 97);
    D(sporocilo, 24);
    L(sporocilo, 17);
    L(sporocilo, 7);
    L(sporocilo, 3);
    Z(sporocilo, 'q', 'n');
    D(sporocilo, 93);
    Z(sporocilo, 's', 'm');
    Z(sporocilo, 'b', 'p');
    L(sporocilo, 61);
    Z(sporocilo, 'p', 'a');
    L(sporocilo, 100);
    L(sporocilo, 94);
    D(sporocilo, 19);
    L(sporocilo, 10);
    L(sporocilo, 31);
    Z(sporocilo, 'h', 'f');
    D(sporocilo, 61);
    D(sporocilo, 97);
    Z(sporocilo, 'l', 'a');
    L(sporocilo, 80);
    D(sporocilo, 22);
    D(sporocilo, 39);
    D(sporocilo, 11);
    D(sporocilo, 71);
    Z(sporocilo, 'w', 'k');
    L(sporocilo, 58);
    L(sporocilo, 77);
    Z(sporocilo, 'a', 'e');
    D(sporocilo, 41);
    D(sporocilo, 47);
    Z(sporocilo, 'm', 'e');
    L(sporocilo, 25);
    D(sporocilo, 9);
    D(sporocilo, 61);
    Z(sporocilo, 'v', 'q');
    L(sporocilo, 34);
    D(sporocilo, 96);
    L(sporocilo, 65);
    D(sporocilo, 64);
    L(sporocilo, 15);
    D(sporocilo, 72);
    D(sporocilo, 87);
    D(sporocilo, 13);
    L(sporocilo, 72);
    Z(sporocilo, 'p', 'i');
    L(sporocilo, 5);
    L(sporocilo, 10);
    Z(sporocilo, 'e', 'w');
    L(sporocilo, 72);
    Z(sporocilo, 't', 'g');
    L(sporocilo, 56);
    Z(sporocilo, 'w', 'd');
    L(sporocilo, 64);
    Z(sporocilo, 'e', 'c');
    D(sporocilo, 63);
    D(sporocilo, 16);
    L(sporocilo, 70);
    D(sporocilo, 40);
    L(sporocilo, 56);
    L(sporocilo, 98);
    D(sporocilo, 90);
    L(sporocilo, 43);
    D(sporocilo, 69);
    D(sporocilo, 69);
    L(sporocilo, 72);
    Z(sporocilo, 'd', 'i');
    D(sporocilo, 33);
    Z(sporocilo, 'v', 'm');
    Z(sporocilo, 'g', 'd');
    D(sporocilo, 94);
    L(sporocilo, 30);
    D(sporocilo, 16);
    Z(sporocilo, 'z', 'z');
    L(sporocilo, 81);
    Z(sporocilo, 'e', 'r');
    Z(sporocilo, 'i', 'y');
    L(sporocilo, 23);
    D(sporocilo, 84);
    L(sporocilo, 73);
    L(sporocilo, 45);
    L(sporocilo, 18);
    D(sporocilo, 79);
    L(sporocilo, 92);
    L(sporocilo, 56);
    D(sporocilo, 65);
    D(sporocilo, 25);
    Z(sporocilo, 'i', 'd');
    D(sporocilo, 88);
    D(sporocilo, 46);
    L(sporocilo, 59);
    D(sporocilo, 93);
    D(sporocilo, 80);
    L(sporocilo, 81);
    Z(sporocilo, 'w', 'm');
    L(sporocilo, 10);
    Z(sporocilo, 'v', 'q');
    D(sporocilo, 17);
    D(sporocilo, 84);
    D(sporocilo, 44);
    L(sporocilo, 58);
    D(sporocilo, 20);
    D(sporocilo, 95);
    Z(sporocilo, 'y', 'c');
    Z(sporocilo, 's', 'h');
    Z(sporocilo, 'i', 'd');
    D(sporocilo, 86);
    D(sporocilo, 52);
    D(sporocilo, 17);
    L(sporocilo, 82);
    L(sporocilo, 62);
    L(sporocilo, 77);
    L(sporocilo, 4);
    L(sporocilo, 68);
    L(sporocilo, 68);
    L(sporocilo, 7);
    Z(sporocilo, 'f', 'x');
    L(sporocilo, 15);
    L(sporocilo, 53);
    Z(sporocilo, 'e', 'n');
    D(sporocilo, 81);
    Z(sporocilo, 'z', 'x');
    L(sporocilo, 32);
    L(sporocilo, 10);
    D(sporocilo, 61);
    D(sporocilo, 19);
    Z(sporocilo, 'a', 'q');
    Z(sporocilo, 'k', 'r');
    D(sporocilo, 67);
    D(sporocilo, 33);
    Z(sporocilo, 'h', 'g');
    Z(sporocilo, 'x', 'x');
    Z(sporocilo, 'c', 'y');
    L(sporocilo, 23);
    Z(sporocilo, 'u', 'f');
    Z(sporocilo, 'h', 'a');
    D(sporocilo, 35);
    Z(sporocilo, 'y', 'q');
    D(sporocilo, 77);
    L(sporocilo, 75);
    Z(sporocilo, 'w', 'w');
    D(sporocilo, 27);
    Z(sporocilo, 'u', 'q');
    L(sporocilo, 80);
    Z(sporocilo, 'm', 'v');
    L(sporocilo, 20);
    L(sporocilo, 42);
    L(sporocilo, 46);
    Z(sporocilo, 'c', 'm');
    D(sporocilo, 22);
    D(sporocilo, 81);
    L(sporocilo, 24);
    Z(sporocilo, 'm', 'z');
    Z(sporocilo, 'n', 'w');
    Z(sporocilo, 'y', 'n');
    D(sporocilo, 17);
    D(sporocilo, 50);
    L(sporocilo, 84);
    Z(sporocilo, 'r', 'd');
    D(sporocilo, 49);
    Z(sporocilo, 'n', 'y');
    D(sporocilo, 98);
    D(sporocilo, 98);
    D(sporocilo, 32);
    D(sporocilo, 97);
    Z(sporocilo, 'b', 'w');
    Z(sporocilo, 'b', 'd');
    Z(sporocilo, 'w', 'y');
    L(sporocilo, 66);
    Z(sporocilo, 'g', 'h');
    L(sporocilo, 5);
    D(sporocilo, 5);
    Z(sporocilo, 'w', 'b');
    L(sporocilo, 83);
    D(sporocilo, 19);
    L(sporocilo, 9);
    D(sporocilo, 27);
    L(sporocilo, 5);
    Z(sporocilo, 'x', 'e');
    L(sporocilo, 70);
    L(sporocilo, 37);
    Z(sporocilo, 'z', 'l');
    L(sporocilo, 12);
    D(sporocilo, 46);
    Z(sporocilo, 's', 'j');
    L(sporocilo, 52);
    Z(sporocilo, 'a', 'g');
    D(sporocilo, 7);
    Z(sporocilo, 'f', 'q');
    D(sporocilo, 2);
    Z(sporocilo, 'b', 'g');
    Z(sporocilo, 'j', 'k');
    L(sporocilo, 30);
    L(sporocilo, 8);
    Z(sporocilo, 'p', 'f');
    D(sporocilo, 20);
    Z(sporocilo, 'i', 'v');
    Z(sporocilo, 'f', 'l');
    D(sporocilo, 9);
    L(sporocilo, 99);
    Z(sporocilo, 'g', 'n');
    D(sporocilo, 69);
    Z(sporocilo, 'h', 'o');
    D(sporocilo, 29);
    L(sporocilo, 52);
    L(sporocilo, 71);
    Z(sporocilo, 'n', 't');
    D(sporocilo, 37);
    L(sporocilo, 15);
    L(sporocilo, 63);
    Z(sporocilo, 'v', 'u');
    D(sporocilo, 98);
    D(sporocilo, 79);
    L(sporocilo, 63);
    Z(sporocilo, 'c', 't');
    L(sporocilo, 93);
    Z(sporocilo, 'e', 'z');
    Z(sporocilo, 'd', 'o');
    Z(sporocilo, 'n', 'b');
    L(sporocilo, 69);
    L(sporocilo, 33);
    D(sporocilo, 58);
    L(sporocilo, 94);
    Z(sporocilo, 'o', 'p');
    D(sporocilo, 54);
    D(sporocilo, 35);
    L(sporocilo, 47);
    D(sporocilo, 82);
    Z(sporocilo, 'g', 'h');
    D(sporocilo, 24);
    Z(sporocilo, 's', 'j');
    D(sporocilo, 76);
    D(sporocilo, 57);
    Z(sporocilo, 'x', 'j');
    D(sporocilo, 86);
    Z(sporocilo, 'b', 'p');
    Z(sporocilo, 'e', 'j');
    D(sporocilo, 37);
    Z(sporocilo, 'd', 'l');
    Z(sporocilo, 'g', 'b');
    D(sporocilo, 92);
    D(sporocilo, 43);
    D(sporocilo, 83);
    Z(sporocilo, 'n', 'z');
    L(sporocilo, 42);
    Z(sporocilo, 'd', 'o');
    L(sporocilo, 95);
    L(sporocilo, 84);
    Z(sporocilo, 'w', 'n');
    L(sporocilo, 53);
    cout<<sporocilo;
    return 0;
}
void L(string &s,int zamik){
    reverse(s.begin(), s.begin()+zamik);
    reverse(s.begin()+zamik, s.end());
    reverse(s.begin(), s.end());
}
void D(string &s,int zamik){
    L(s, s.length()-zamik);
}
void Z(string &s,char znak1,char znak2){
int l = s.length();
    for (int i=0;i<l;i++) {
        if (s[i] == znak1)
            s[i] = znak2;
        else if (s[i] == znak2)
            s[i] = znak1;
    }
}
